### ISSUE TITLE
[Bug] Unable to install development version on Xbox Game Pass

### ISSUE THREAD

**Issue by gaby** [Externoak/A32NX-installer#12]
My game is installed with Xbox Game Pass which creates a very long destination folder, when installing the Development version the following error shows up: 

`
Folder could not be unzipped, failed reason: FileNotFoundError(2, 'No such file or directory')!
`

This doesn't happen when installing the latest Stable version. It only happens with the "development" version.

**Comment by Externoak** [comment]
It seems to be quite a strange path to work with, please check FAQs found here [FAQs](https://github.com/Externoak/A32NX-installer#faqs). 
Try this:

To quote FAQs:
Q: Downloader error: "Folder could not be unzipped, failed reason: FileNotFound".

A: It is most likely you have MSFS installed in a WpSystem file path, this directory is write-protected and cannot be written to. The best solution is to select a temporary location for example your Desktop then download the A32NX folder there and move it manually to your Community folder.

I will keep an eye on this error but since it's not something a lot of users are able to reproduce there is not much we can look into.

**Comment by gaby** [comment]
I've been testing this, and it seems it just fails midway through the unzipping process. The folder structure between a `stable` and `development` is pretty much the same, so is the unzipping process. 🤔

One suggestion I saw was using a temporary folder to unzip and then moving the files to the final destination. I will give that a try in my fork tonight.

**Comment by Externoak** [comment]
Nice work, give it a try and let me know. I'm afraid I can't help you since I do not have this WpSystem path and cannot reproduce it on my side. All I know is that it's a strange Windows path with some weird permissions and characteristics.

**Comment by Androkiller** [comment]
+1 on the issue but mine is the steam version.

Changing dir and on other disks has not helped nor running as admin.

I checked the NTFS permissions and created more to allow everyone full control to a temp dir and this did not help either.
![image](https://user-images.githubusercontent.com/25016806/113645225-6507fc80-967e-11eb-870a-91b54a435927.png)

**Comment by gaby** [comment]
@Androkiller I think this installer is deprecated, the flybywiresim team released an official installer which solves this issue. 

You can find it here: https://github.com/flybywiresim/installer/
