### ISSUE TITLE
Antivirus Alert : FileRepMalware

### ISSUE THREAD

**Issue by CondormanFr** [Externoak/A32NX-installer#13]
Hello,
Avast reports me an exception with the A32NX_Downloader.Exe : FileRepMalware.
What explain that ?

![2020-11-17 07_58_32-Avast Antivirus Gratuit](https://user-images.githubusercontent.com/2799574/99356795-12829b00-28ab-11eb-93f2-3b6bfaa48529.png)

**Comment by Externoak** [comment]
It is possible that some antivirus flag the exe as a harmful program since it is not a signed exe file, you should whitelist it. 

Also as explained in [FAQs](https://github.com/Externoak/A32NX-installer#faqs)

Q: I don't trust running an unknown exe file.

A: The source code of the Downloader is available for all to view. The exe file will always be automatically created in an isolated environment using Github workflows, you are also free to scan the exe file using an antivirus or Virustotal.

In the workflow there is also an automated AV scan using Virustotal to make sure all is in check. Here are the results [Virustotal](https://www.virustotal.com/gui/file/a7f1e48b32c966af2d17bb8b64e135475ef6bf08181362350c6cd79b0ec67012/detection/f-a7f1e48b32c966af2d17bb8b64e135475ef6bf08181362350c6cd79b0ec67012-1605527970)
